{
  flake,
  lib,
  pkgs,
  config,
  ...
}:
{
  imports = [
    flake.inputs.dms.homeModules.default
    flake.inputs.dms.homeModules.niri
    flake.inputs.dms-plugin-registry.modules.default
  ];

  programs.dank-material-shell = {
    enable = true;

    systemd = {
      enable = true; # Systemd service for auto-start
      restartIfChanged = true; # Auto-restart dms.service when dms-shell changes
    };

    niri.includes = {
      enable = true; # Enable config includes hack. Enabled by default.

      override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [
        # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        "alttab" # Please note that niri will throw an error if any of these files are missing.
        "binds"
        "colors"
        "cursor"
        "layout"
        "outputs"
        "windowrules"
        "wpblur"
      ];
    };

    # Core features
    enableSystemMonitoring = true; # System monitoring widgets (dgop)
    enableVPN = true; # VPN management widget
    enableDynamicTheming = true; # Wallpaper-based theming (matugen)
    enableAudioWavelength = true; # Audio visualizer (cava)
    enableCalendarEvents = true; # Calendar integration (khal)
    enableClipboardPaste = true; # Manage clipboard history

    plugins = {
      dankBatteryAlerts.enable = true;
    };
  };

  # Avoid conflict with niri-flake
  #systemd.user.services.niri-flake-polkit.enable = false;

  # Configure Hyprland
  wayland.windowManager.hyprland.settings.source = [
    "${config.xdg.configHome}/hypr/dms/outputs.conf"
    "${config.xdg.configHome}/hypr/dms/colors.conf"
  ];

  # Configure kitty to use DMS config
  programs.kitty.extraConfig = "
      include dank-tabs.conf
      include dank-theme.conf
    ";

  # Configure GTK to use DMS themes
  gtk = {
    # Include dank linux configuration
    gtk3.extraCss = "@import url(\"dank-colors.css\");";
    gtk4.extraCss = "@import url(\"dank-colors.css\");";
  };

  # For Linux WallpaperEngine Plugin
  services.linux-wallpaperengine.enable = true;
  # Clear linux-wallpaperengine service as it is managed by DMS
  systemd.user.services."linux-wallpaperengine".Service.ExecStart =
    lib.mkForce "${pkgs.coreutils}/bin/echo disabled";

  # Configure Zen-browser with DMS
  # programs.zen-browser.profiles.default.settings."toolkit.legacyUserProfileCustomizations.stylesheets" =
  #  true;
  #home.file."${config.xdg.configHome}/zen/default/chrome/userChrome.css".source =
  #config.lib.file.mkOutOfStoreSymlink "${config.xdg.configHome}/DankMaterialShell/zen.css";
}
