# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4bece4ed-5ad6-4367-8859-dfdddc25b9f4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9AF3-D3E7";
      fsType = "vfat";
    };

  fileSystems."/shared" =
    { device = "/dev/disk/by-uuid/5ADEB2E56874CEB0";
      fsType = "ntfs";
      options = [ "rw" "uid=1000 gid=100" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b1165bde-703e-400d-937d-637a168c92fd"; }
    ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.nvidia.prime = {
    offload.enable = true;
    nvidiaBusId = "PCI:1:0:0";
    intelBusId = "PCI:0:2:0";
  };

  # Enable bluetooth
  hardware.bluetooth.enable = true;
 
  virtualisation.docker.enable = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
