# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-intel" ];
  boot.blacklistedKernelModules = [ "hid-sensor-hub" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "i915.enable_psr=0"
  ];

  # Setup keyfile
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/C455-020A";
      fsType = "vfat";
    };

  boot.initrd.luks.devices."luks-9eeb24d8-4901-49a2-8d83-39154372aa37".device = "/dev/disk/by-uuid/9eeb24d8-4901-49a2-8d83-39154372aa37";

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e63b4e7c-523b-4a93-a102-3d71fa901bc7";
      fsType = "ext4";
    };

  # Enable swap on luks
  boot.initrd.luks.devices."luks-68d59294-0483-4853-a0b7-5d71c1e3e8ab".device = "/dev/disk/by-uuid/68d59294-0483-4853-a0b7-5d71c1e3e8ab";
  boot.initrd.luks.devices."luks-68d59294-0483-4853-a0b7-5d71c1e3e8ab".keyFile = "/crypto_keyfile.bin";

  swapDevices =
    [{ device = "/dev/disk/by-uuid/fee77592-7902-4b96-8ea6-2b882477b70e"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp166s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable bluetooth
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  virtualisation.docker.enable = true;
  virtualisation.libvirtd.enable = true;
}
